// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortlandLocalShopsApi.Models;

#nullable disable

namespace PortlandLocalShopsApi.Migrations
{
    [DbContext(typeof(PortlandLocalShopsApiContext))]
    [Migration("20230401002318_updateFakerSyntax4")]
    partial class updateFakerSyntax4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PortlandLocalShopsApi.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MusicType")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PartOfTown")
                        .HasColumnType("longtext");

                    b.Property<string>("StoreType")
                        .HasColumnType("longtext");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            ShopId = 5,
                            MusicType = "Distinctio possimus ab odio aut adipisci.",
                            Name = "Wisoky-Parker",
                            PartOfTown = "Tempora voluptate perspiciatis ut consectetur eos.",
                            StoreType = "Quo corrupti sint mollitia occaecati ducimus."
                        },
                        new
                        {
                            ShopId = 6,
                            MusicType = "Asperiores quia deserunt et.",
                            Name = "Daugherty, Schinner and Heidenreich",
                            PartOfTown = "Maxime ducimus nostrum ratione ipsa et aspernatur.",
                            StoreType = "Et tempora et minima et."
                        },
                        new
                        {
                            ShopId = 7,
                            MusicType = "Rerum cupiditate aut dolor sint velit nulla impedit.",
                            Name = "Bahringer Inc and Sons",
                            PartOfTown = "Tenetur voluptatem et quasi quod magni doloremque nulla saepe quis.",
                            StoreType = "Delectus omnis fuga error tempore laboriosam voluptatem in."
                        },
                        new
                        {
                            ShopId = 8,
                            MusicType = "Officia sequi et quasi eaque voluptatem illum eum tempore.",
                            Name = "Gleichner, Feeney and Fadel",
                            PartOfTown = "Optio at quasi natus ipsam quas.",
                            StoreType = "Id adipisci consectetur sapiente."
                        },
                        new
                        {
                            ShopId = 9,
                            MusicType = "Ut inventore aut quaerat culpa quia.",
                            Name = "Harvey-Schimmel",
                            PartOfTown = "Repellendus ea non et ea sunt mollitia quas.",
                            StoreType = "Nisi doloremque iste minima nam placeat officiis officiis."
                        },
                        new
                        {
                            ShopId = 10,
                            MusicType = "Nobis quasi qui quam.",
                            Name = "Hudson, Corkery and Schimmel",
                            PartOfTown = "Ut laudantium natus rerum.",
                            StoreType = "Labore officiis beatae tenetur vel at et."
                        },
                        new
                        {
                            ShopId = 11,
                            MusicType = "Aperiam minus est similique quia corporis dignissimos.",
                            Name = "Harvey-Weimann",
                            PartOfTown = "Voluptatem inventore necessitatibus enim neque molestiae cum et quam.",
                            StoreType = "Temporibus minus culpa consequatur enim quaerat ea inventore voluptatem."
                        },
                        new
                        {
                            ShopId = 12,
                            MusicType = "Iusto voluptatem et ratione quam quia quaerat quis vitae.",
                            Name = "Goyette, Baumbach and King",
                            PartOfTown = "Maxime qui et in.",
                            StoreType = "Natus id quo suscipit sunt."
                        },
                        new
                        {
                            ShopId = 13,
                            MusicType = "Sit pariatur placeat quis velit minus hic.",
                            Name = "Jerde-O'Connell",
                            PartOfTown = "Dolores et molestiae error non veritatis non earum magni.",
                            StoreType = "Mollitia earum vero odit architecto quae veritatis aperiam laudantium."
                        },
                        new
                        {
                            ShopId = 14,
                            MusicType = "Tempore perspiciatis voluptatem aut.",
                            Name = "Bins-Batz",
                            PartOfTown = "Sequi voluptas quo eligendi est nulla aut qui vero.",
                            StoreType = "Voluptatum distinctio corrupti itaque sed accusamus voluptates dignissimos similique."
                        },
                        new
                        {
                            ShopId = 15,
                            MusicType = "Ducimus repudiandae voluptatibus in quos earum.",
                            Name = "Conn Inc and Sons",
                            PartOfTown = "Similique atque nemo doloremque.",
                            StoreType = "Sequi et quisquam expedita unde voluptatem et."
                        },
                        new
                        {
                            ShopId = 16,
                            MusicType = "Fugiat quam libero sint eos incidunt.",
                            Name = "Collier-Larson",
                            PartOfTown = "Sapiente architecto quia voluptas eum repellendus.",
                            StoreType = "Nostrum in sint non eaque est quia."
                        },
                        new
                        {
                            ShopId = 17,
                            MusicType = "Tempora autem praesentium aut.",
                            Name = "Barrows-McKenzie",
                            PartOfTown = "Sed cumque sint voluptatem voluptas omnis provident delectus qui.",
                            StoreType = "Reprehenderit et quas consequatur."
                        },
                        new
                        {
                            ShopId = 18,
                            MusicType = "Veniam illo rem perspiciatis nisi.",
                            Name = "Schneider Group",
                            PartOfTown = "Laborum natus et non.",
                            StoreType = "Vero veritatis ut quis eligendi consequatur."
                        },
                        new
                        {
                            ShopId = 19,
                            MusicType = "Commodi voluptatem dolore fugit ut.",
                            Name = "Effertz, McGlynn and Ledner",
                            PartOfTown = "Quo distinctio nostrum magnam culpa.",
                            StoreType = "Et consequuntur est officia."
                        },
                        new
                        {
                            ShopId = 20,
                            MusicType = "Consequatur et natus sed.",
                            Name = "Bogisich-Ryan",
                            PartOfTown = "Culpa nostrum est qui qui qui laborum magnam.",
                            StoreType = "Voluptatum quod esse temporibus dolore aut."
                        },
                        new
                        {
                            ShopId = 21,
                            MusicType = "Nihil odit facere veniam architecto commodi.",
                            Name = "Cronin-Treutel",
                            PartOfTown = "Et rerum reiciendis dignissimos voluptate ut ipsum rerum dolore placeat.",
                            StoreType = "A et et sit autem libero aspernatur sunt aut ut."
                        },
                        new
                        {
                            ShopId = 22,
                            MusicType = "Reiciendis ut recusandae pariatur.",
                            Name = "Brekke LLC",
                            PartOfTown = "Sed dolorem placeat illum ducimus.",
                            StoreType = "Est qui omnis sapiente non perspiciatis voluptas animi."
                        },
                        new
                        {
                            ShopId = 23,
                            MusicType = "Et est aut ut quia ut ea architecto.",
                            Name = "Glover-Pouros",
                            PartOfTown = "Eveniet cumque laudantium aut.",
                            StoreType = "Odit corrupti saepe qui sed quam beatae iusto quae."
                        },
                        new
                        {
                            ShopId = 24,
                            MusicType = "Fuga qui sit fuga eum debitis dolor placeat molestiae dolor.",
                            Name = "Baumbach Group",
                            PartOfTown = "Officiis pariatur accusamus ullam officiis voluptatum quasi sed saepe et.",
                            StoreType = "Porro voluptatibus aliquid id eos."
                        },
                        new
                        {
                            ShopId = 25,
                            MusicType = "Aut enim architecto ea cum ipsa iure.",
                            Name = "Schimmel, Maggio and Metz",
                            PartOfTown = "Veritatis facere sed ex quam.",
                            StoreType = "Quam dolorem nostrum eligendi illo nesciunt natus."
                        },
                        new
                        {
                            ShopId = 26,
                            MusicType = "Animi nihil praesentium autem occaecati.",
                            Name = "Bogisich LLC",
                            PartOfTown = "Et eum est temporibus mollitia sit repellat.",
                            StoreType = "Architecto quibusdam libero odio voluptatum minima."
                        },
                        new
                        {
                            ShopId = 27,
                            MusicType = "Necessitatibus nihil hic vitae minus et voluptas eaque praesentium.",
                            Name = "Nikolaus Group",
                            PartOfTown = "Sit enim rerum dolor sapiente.",
                            StoreType = "Ipsum voluptatem id quia nisi consequatur porro occaecati."
                        },
                        new
                        {
                            ShopId = 28,
                            MusicType = "Quo dicta minima mollitia.",
                            Name = "Runte Inc and Sons",
                            PartOfTown = "Tenetur minima cum in porro facere aut illum et.",
                            StoreType = "Similique nulla temporibus tenetur quia optio autem nemo."
                        },
                        new
                        {
                            ShopId = 29,
                            MusicType = "Aut rerum occaecati unde officia quia et culpa animi asperiores.",
                            Name = "Huel LLC",
                            PartOfTown = "Similique tenetur quia illum corporis error.",
                            StoreType = "Praesentium asperiores modi harum et cupiditate qui impedit mollitia."
                        },
                        new
                        {
                            ShopId = 30,
                            MusicType = "Culpa provident ipsam voluptas in.",
                            Name = "Waelchi, McGlynn and Brekke",
                            PartOfTown = "Sit minima distinctio totam et eos est.",
                            StoreType = "Quia repellat temporibus est omnis rerum nostrum."
                        },
                        new
                        {
                            ShopId = 31,
                            MusicType = "Cumque impedit deleniti unde alias.",
                            Name = "Emmerich Group",
                            PartOfTown = "Doloribus est ab velit et nisi ut inventore provident est.",
                            StoreType = "Dolorem necessitatibus ut quia quasi et et voluptatibus cupiditate."
                        },
                        new
                        {
                            ShopId = 32,
                            MusicType = "Totam ea adipisci necessitatibus.",
                            Name = "Bayer Inc and Sons",
                            PartOfTown = "Ipsum optio facilis velit cumque doloribus.",
                            StoreType = "Ipsum quasi non alias dicta fuga enim autem."
                        },
                        new
                        {
                            ShopId = 33,
                            MusicType = "Architecto qui suscipit autem corporis eveniet.",
                            Name = "Anderson, Beahan and Lehner",
                            PartOfTown = "Eaque alias fugit necessitatibus culpa velit.",
                            StoreType = "Sequi ipsum nostrum et molestiae consectetur inventore facilis laborum in."
                        },
                        new
                        {
                            ShopId = 34,
                            MusicType = "Molestias iusto quis ea et minus id repudiandae.",
                            Name = "Lang-Crona",
                            PartOfTown = "Reiciendis vel dolorem soluta ducimus.",
                            StoreType = "Sit reiciendis illum officia mollitia."
                        },
                        new
                        {
                            ShopId = 35,
                            MusicType = "Cum accusantium nisi commodi quam mollitia modi delectus.",
                            Name = "Larkin-Gerhold",
                            PartOfTown = "Ut dignissimos autem distinctio molestiae facilis consequatur quaerat.",
                            StoreType = "Rerum ut maiores neque est corrupti ullam corrupti."
                        },
                        new
                        {
                            ShopId = 36,
                            MusicType = "Velit eaque placeat doloribus qui blanditiis quis et.",
                            Name = "Klein-Braun",
                            PartOfTown = "Ratione labore voluptas distinctio ullam autem at ducimus voluptatem consequatur.",
                            StoreType = "Officia impedit et esse harum."
                        },
                        new
                        {
                            ShopId = 37,
                            MusicType = "Esse enim ut necessitatibus ea impedit.",
                            Name = "Leannon-Schaefer",
                            PartOfTown = "Amet eveniet aut sit vel est.",
                            StoreType = "Est iusto a occaecati."
                        },
                        new
                        {
                            ShopId = 38,
                            MusicType = "Unde in saepe iusto omnis.",
                            Name = "Cremin, Breitenberg and Adams",
                            PartOfTown = "Quasi laborum sed incidunt.",
                            StoreType = "Ut et est voluptate perferendis eveniet."
                        },
                        new
                        {
                            ShopId = 39,
                            MusicType = "Incidunt voluptas illum aut voluptatem ad.",
                            Name = "Prohaska Group",
                            PartOfTown = "Eius quod ipsa et eum amet sunt reprehenderit explicabo.",
                            StoreType = "Fugit est quod distinctio possimus."
                        },
                        new
                        {
                            ShopId = 40,
                            MusicType = "Incidunt ut harum incidunt facilis.",
                            Name = "Streich-Kessler",
                            PartOfTown = "Expedita voluptatum voluptatibus cum cupiditate quibusdam laudantium sint et.",
                            StoreType = "Quo nulla possimus dolor aut atque."
                        },
                        new
                        {
                            ShopId = 41,
                            MusicType = "Expedita animi architecto ullam et eos est hic dolorum sed.",
                            Name = "Hirthe LLC",
                            PartOfTown = "Minus ut aliquam officia voluptatem nisi.",
                            StoreType = "Quo et voluptate aliquid reiciendis quia commodi."
                        },
                        new
                        {
                            ShopId = 42,
                            MusicType = "Doloribus qui similique cupiditate.",
                            Name = "Kohler, Emmerich and DuBuque",
                            PartOfTown = "Iure hic facilis et quae eum molestiae a omnis odit.",
                            StoreType = "Laudantium aut minus fugit."
                        },
                        new
                        {
                            ShopId = 43,
                            MusicType = "Rerum culpa id repudiandae mollitia est quod suscipit aliquam.",
                            Name = "Yundt Inc and Sons",
                            PartOfTown = "Adipisci doloremque vitae ex dicta.",
                            StoreType = "Maiores est illo consequuntur nostrum aut voluptatem ea ratione."
                        },
                        new
                        {
                            ShopId = 44,
                            MusicType = "Distinctio architecto qui cum omnis vel sit doloribus.",
                            Name = "Langosh-Wilderman",
                            PartOfTown = "Modi rerum porro eveniet dicta quibusdam.",
                            StoreType = "Ipsam exercitationem neque voluptate facilis voluptates eum labore quaerat."
                        },
                        new
                        {
                            ShopId = 45,
                            MusicType = "Itaque libero modi ipsa.",
                            Name = "Nienow, Legros and Conroy",
                            PartOfTown = "Reiciendis recusandae ducimus est.",
                            StoreType = "Repudiandae et incidunt aliquid voluptas eius tempora ut tenetur est."
                        },
                        new
                        {
                            ShopId = 46,
                            MusicType = "Harum quos aliquam error.",
                            Name = "Waters-Douglas",
                            PartOfTown = "A totam modi qui quo reiciendis suscipit et delectus id.",
                            StoreType = "Libero illum animi suscipit cupiditate aspernatur."
                        },
                        new
                        {
                            ShopId = 47,
                            MusicType = "Suscipit sed dignissimos mollitia.",
                            Name = "Grady-Rau",
                            PartOfTown = "Sunt recusandae necessitatibus occaecati harum qui fuga ipsam atque vitae.",
                            StoreType = "Omnis error aliquam illo aut velit."
                        },
                        new
                        {
                            ShopId = 48,
                            MusicType = "Esse quisquam dolore recusandae quo quas est voluptatem sed.",
                            Name = "Dietrich, Senger and Kuhlman",
                            PartOfTown = "Non natus quis et id saepe.",
                            StoreType = "Magni dolor eveniet repellat."
                        },
                        new
                        {
                            ShopId = 49,
                            MusicType = "Praesentium omnis consequatur sequi qui rerum fugiat quod.",
                            Name = "Smitham-Rowe",
                            PartOfTown = "Ducimus asperiores aut atque.",
                            StoreType = "Nulla facere enim totam."
                        },
                        new
                        {
                            ShopId = 50,
                            MusicType = "Delectus at eos molestiae nisi pariatur dolor enim magni non.",
                            Name = "Schoen-Trantow",
                            PartOfTown = "Rerum enim aut voluptas facere at cumque officia eum.",
                            StoreType = "Modi quod corporis et autem est maxime nemo."
                        },
                        new
                        {
                            ShopId = 51,
                            MusicType = "Velit nesciunt laboriosam sint porro illum earum aut veritatis.",
                            Name = "Brown, Considine and Walter",
                            PartOfTown = "Voluptas a omnis dignissimos est est sapiente eos illo voluptas.",
                            StoreType = "Et asperiores minus eligendi cum ut officiis ut similique nemo."
                        },
                        new
                        {
                            ShopId = 52,
                            MusicType = "Inventore quibusdam aut animi nesciunt modi.",
                            Name = "Christiansen-Moore",
                            PartOfTown = "Tempore aut et adipisci libero voluptas illo qui laborum placeat.",
                            StoreType = "Voluptatem quia iste quae aperiam sint."
                        },
                        new
                        {
                            ShopId = 53,
                            MusicType = "Eaque id consectetur iusto est autem nam et officiis explicabo.",
                            Name = "Bradtke, Shanahan and Aufderhar",
                            PartOfTown = "Debitis tempore et dicta aliquid ad.",
                            StoreType = "Officia sequi non autem architecto qui qui nesciunt."
                        },
                        new
                        {
                            ShopId = 54,
                            MusicType = "Occaecati dolorem commodi dolorum occaecati quidem ut est atque corporis.",
                            Name = "Feeney, Hamill and Turcotte",
                            PartOfTown = "Et sed commodi molestiae est vel perspiciatis enim velit fugit.",
                            StoreType = "Quasi minus quibusdam excepturi molestias."
                        },
                        new
                        {
                            ShopId = 55,
                            MusicType = "Dolore fugit a voluptas iste necessitatibus voluptas molestiae assumenda.",
                            Name = "Labadie LLC",
                            PartOfTown = "Molestiae ab assumenda iure sunt ut necessitatibus enim sint.",
                            StoreType = "Adipisci provident unde qui."
                        },
                        new
                        {
                            ShopId = 56,
                            MusicType = "Quia magni quos dolor rem accusamus exercitationem aperiam omnis.",
                            Name = "O'Connell, Kiehn and Hansen",
                            PartOfTown = "Sed eveniet ea voluptatem neque nihil eos impedit omnis.",
                            StoreType = "Consequatur sunt labore adipisci occaecati asperiores."
                        },
                        new
                        {
                            ShopId = 57,
                            MusicType = "Doloremque aut harum fugit natus.",
                            Name = "Stehr LLC",
                            PartOfTown = "Omnis et velit veniam illum aspernatur et.",
                            StoreType = "Voluptatem sit facere deserunt in explicabo."
                        },
                        new
                        {
                            ShopId = 58,
                            MusicType = "Error aut dolorem quam sapiente est illum neque.",
                            Name = "Conroy-Gleichner",
                            PartOfTown = "Et maxime vero qui eum id dolores.",
                            StoreType = "Est recusandae maxime non a."
                        },
                        new
                        {
                            ShopId = 59,
                            MusicType = "Odit voluptatibus et repellat odio natus.",
                            Name = "Simonis LLC",
                            PartOfTown = "Aspernatur perspiciatis ad dolorem molestias veniam molestiae explicabo repudiandae.",
                            StoreType = "Commodi aperiam odit est qui."
                        },
                        new
                        {
                            ShopId = 60,
                            MusicType = "Neque autem numquam debitis veritatis.",
                            Name = "Rutherford-Mitchell",
                            PartOfTown = "Velit quas aut eos nulla dolore debitis voluptate.",
                            StoreType = "Maiores molestiae quis maxime."
                        },
                        new
                        {
                            ShopId = 61,
                            MusicType = "Nisi earum laudantium ex.",
                            Name = "Wunsch, Ankunding and Bartell",
                            PartOfTown = "Id commodi ut culpa.",
                            StoreType = "Dolores quibusdam et dolores ipsum rem rerum."
                        },
                        new
                        {
                            ShopId = 62,
                            MusicType = "Laboriosam voluptatem eum explicabo.",
                            Name = "Mante-Bode",
                            PartOfTown = "Quos neque perspiciatis libero adipisci.",
                            StoreType = "Iusto eum delectus odit quasi."
                        },
                        new
                        {
                            ShopId = 63,
                            MusicType = "Earum voluptatem enim sunt optio nulla ut eius.",
                            Name = "Jaskolski Group",
                            PartOfTown = "Dolorum adipisci est maxime.",
                            StoreType = "Molestias voluptatem vero eveniet aliquid odit mollitia minima voluptatem quo."
                        },
                        new
                        {
                            ShopId = 64,
                            MusicType = "Ipsam et sit harum incidunt repellat nesciunt quo amet.",
                            Name = "Farrell, Rosenbaum and Cummerata",
                            PartOfTown = "Dicta suscipit mollitia eaque assumenda.",
                            StoreType = "Sit rerum temporibus et impedit."
                        },
                        new
                        {
                            ShopId = 65,
                            MusicType = "Ut aut deserunt at est soluta veritatis sit explicabo.",
                            Name = "Hudson, Hand and Kertzmann",
                            PartOfTown = "Magni tenetur sit nulla ratione eligendi voluptates minima.",
                            StoreType = "Ipsa aut voluptatibus facilis."
                        },
                        new
                        {
                            ShopId = 66,
                            MusicType = "Soluta id ut esse.",
                            Name = "Mann LLC",
                            PartOfTown = "Enim et quo consequuntur id sit labore consequatur et aut.",
                            StoreType = "Cum odio quas occaecati provident consequuntur est est."
                        },
                        new
                        {
                            ShopId = 67,
                            MusicType = "Aut reiciendis hic architecto eveniet incidunt fugit fugit maiores culpa.",
                            Name = "Stoltenberg LLC",
                            PartOfTown = "Saepe labore est eligendi doloribus soluta labore.",
                            StoreType = "Autem et voluptatem nesciunt aperiam excepturi."
                        },
                        new
                        {
                            ShopId = 68,
                            MusicType = "Qui ipsam quidem aut natus.",
                            Name = "Miller, Hessel and Effertz",
                            PartOfTown = "Nulla et et molestiae possimus debitis vero quasi accusamus optio.",
                            StoreType = "Praesentium veritatis saepe voluptatem et."
                        },
                        new
                        {
                            ShopId = 69,
                            MusicType = "Accusamus dicta atque in aut autem impedit dolorum impedit.",
                            Name = "Stoltenberg-Kirlin",
                            PartOfTown = "Aliquid qui minima culpa quia non provident a est similique.",
                            StoreType = "Alias eligendi ipsa sequi et."
                        },
                        new
                        {
                            ShopId = 70,
                            MusicType = "Illo ipsam placeat voluptas quidem facilis inventore nam velit cupiditate.",
                            Name = "Beatty, Kertzmann and Greenholt",
                            PartOfTown = "Vel aut dolores delectus.",
                            StoreType = "Non velit impedit numquam iure vel molestiae accusantium vero."
                        },
                        new
                        {
                            ShopId = 71,
                            MusicType = "Sunt ut non excepturi iste quidem et rem aut.",
                            Name = "Johns, Zieme and Stoltenberg",
                            PartOfTown = "Sint accusantium dolor voluptatum ea.",
                            StoreType = "Deserunt saepe voluptate cumque sint."
                        },
                        new
                        {
                            ShopId = 72,
                            MusicType = "Pariatur maxime quod est et provident iste et voluptatum.",
                            Name = "Gislason LLC",
                            PartOfTown = "Eos cum quaerat minima et.",
                            StoreType = "Illo nihil ducimus facilis molestias."
                        },
                        new
                        {
                            ShopId = 73,
                            MusicType = "Culpa et vel sed.",
                            Name = "Kovacek-Hickle",
                            PartOfTown = "Molestiae sint dolor odit ea.",
                            StoreType = "Provident numquam voluptates et magnam tempore occaecati repellat vel incidunt."
                        },
                        new
                        {
                            ShopId = 74,
                            MusicType = "Nihil veritatis tempore delectus.",
                            Name = "Turcotte, Bernier and Rau",
                            PartOfTown = "Vitae quibusdam ipsum sed doloremque voluptatibus sed eaque non quos.",
                            StoreType = "Ut vel consequuntur rerum possimus delectus quo et nihil."
                        },
                        new
                        {
                            ShopId = 75,
                            MusicType = "Non nulla aperiam libero dignissimos.",
                            Name = "Murazik, Kertzmann and O'Reilly",
                            PartOfTown = "Laudantium quae atque ad dolore aut non at fugiat at.",
                            StoreType = "Ut corrupti culpa facilis fugiat error molestiae."
                        },
                        new
                        {
                            ShopId = 76,
                            MusicType = "Qui dicta voluptates et inventore.",
                            Name = "Schmidt Inc and Sons",
                            PartOfTown = "Voluptas minima at iure ipsam quidem delectus consequuntur ratione et.",
                            StoreType = "Veritatis aut iure molestias expedita et sed."
                        },
                        new
                        {
                            ShopId = 77,
                            MusicType = "Ipsam nihil et voluptatem laborum.",
                            Name = "Goldner, McCullough and Batz",
                            PartOfTown = "Ea ea a et maiores.",
                            StoreType = "Facilis qui quo et beatae praesentium at."
                        },
                        new
                        {
                            ShopId = 78,
                            MusicType = "Qui suscipit expedita deleniti asperiores aliquid.",
                            Name = "Kub-Pfeffer",
                            PartOfTown = "Eos qui dolorem omnis aut consequuntur.",
                            StoreType = "Voluptatibus sit unde sit dolor et optio qui."
                        },
                        new
                        {
                            ShopId = 79,
                            MusicType = "Ipsa omnis aut architecto corporis.",
                            Name = "Lowe, Bailey and Hintz",
                            PartOfTown = "Similique nemo laboriosam quam id soluta omnis non.",
                            StoreType = "Quia nobis exercitationem consequatur quia facere id perferendis nihil."
                        },
                        new
                        {
                            ShopId = 80,
                            MusicType = "Nobis necessitatibus a numquam quod vel inventore.",
                            Name = "Tromp, Kuhlman and Emard",
                            PartOfTown = "Quo alias ut voluptatem dolores adipisci asperiores.",
                            StoreType = "Magnam unde ea at deleniti deserunt praesentium maxime inventore accusamus."
                        },
                        new
                        {
                            ShopId = 81,
                            MusicType = "Nobis ut numquam culpa explicabo molestiae voluptatibus.",
                            Name = "Schinner Inc and Sons",
                            PartOfTown = "Quibusdam sed nisi occaecati consequatur et.",
                            StoreType = "Et magni voluptatem culpa est quia aut assumenda sed incidunt."
                        },
                        new
                        {
                            ShopId = 82,
                            MusicType = "Nam rerum pariatur quaerat iure harum ut.",
                            Name = "Quigley LLC",
                            PartOfTown = "Minima inventore a voluptatem maxime dicta voluptas corporis deserunt nesciunt.",
                            StoreType = "Sunt assumenda qui est autem."
                        },
                        new
                        {
                            ShopId = 83,
                            MusicType = "Et sit esse alias.",
                            Name = "Murphy-Stamm",
                            PartOfTown = "Alias autem qui est soluta doloremque doloribus placeat qui at.",
                            StoreType = "Magni accusantium provident repellendus quod non."
                        },
                        new
                        {
                            ShopId = 84,
                            MusicType = "Consequatur et est voluptas iusto inventore sed sunt.",
                            Name = "Schaden-Ernser",
                            PartOfTown = "In quisquam et laudantium ex possimus.",
                            StoreType = "Harum ducimus ullam modi dolor velit quo rerum aut voluptas."
                        },
                        new
                        {
                            ShopId = 85,
                            MusicType = "Sapiente provident debitis quasi deserunt ut placeat molestiae.",
                            Name = "Cartwright, Mitchell and Schuppe",
                            PartOfTown = "Dolor facilis autem inventore magni delectus vel non voluptas.",
                            StoreType = "Assumenda esse repudiandae nobis sint."
                        },
                        new
                        {
                            ShopId = 86,
                            MusicType = "Placeat pariatur quae ut molestias ad rerum optio minima vitae.",
                            Name = "Luettgen-Dare",
                            PartOfTown = "Ut quam reiciendis repudiandae illo accusantium beatae explicabo et quo.",
                            StoreType = "Dolorem voluptatem quia et quas minima iure corrupti."
                        },
                        new
                        {
                            ShopId = 87,
                            MusicType = "Esse saepe quae ducimus atque.",
                            Name = "Adams, Gutkowski and Metz",
                            PartOfTown = "Dolor nulla id ea ipsa quasi et.",
                            StoreType = "Et corrupti sed impedit ad a officiis."
                        },
                        new
                        {
                            ShopId = 88,
                            MusicType = "Aut voluptate ipsum facilis eius.",
                            Name = "Hoppe, Gleason and Hansen",
                            PartOfTown = "Natus quis et qui doloribus.",
                            StoreType = "Molestias eos tempore dicta est officiis debitis iusto tempora eum."
                        },
                        new
                        {
                            ShopId = 89,
                            MusicType = "Dicta harum qui perspiciatis labore qui fuga.",
                            Name = "Kautzer Group",
                            PartOfTown = "Et recusandae excepturi illum necessitatibus commodi est quasi non.",
                            StoreType = "Et repudiandae facere maxime a."
                        },
                        new
                        {
                            ShopId = 90,
                            MusicType = "Reiciendis quos quia pariatur.",
                            Name = "Treutel Group",
                            PartOfTown = "Et repudiandae cumque occaecati quia.",
                            StoreType = "Facere et iusto voluptates velit qui."
                        },
                        new
                        {
                            ShopId = 91,
                            MusicType = "Ut laboriosam quisquam repellendus eum ea earum veniam.",
                            Name = "Stark Inc and Sons",
                            PartOfTown = "Qui ab magnam in.",
                            StoreType = "Perspiciatis quae ut quidem voluptates accusantium."
                        },
                        new
                        {
                            ShopId = 92,
                            MusicType = "Totam sint excepturi quibusdam quasi qui inventore reprehenderit illum sit.",
                            Name = "Graham, Brakus and Zemlak",
                            PartOfTown = "Ipsa quia suscipit repudiandae.",
                            StoreType = "Qui voluptas maiores omnis."
                        },
                        new
                        {
                            ShopId = 93,
                            MusicType = "Laudantium fugit sit sed maiores fugit delectus ipsum molestiae.",
                            Name = "Gleason Group",
                            PartOfTown = "Vel aut ullam ut tempore.",
                            StoreType = "Magnam ut excepturi quis eos consequuntur qui."
                        },
                        new
                        {
                            ShopId = 94,
                            MusicType = "Amet voluptatem qui consequatur voluptatem deserunt officia.",
                            Name = "Koepp-Sipes",
                            PartOfTown = "Sunt praesentium dicta qui est.",
                            StoreType = "Commodi odio id reiciendis soluta."
                        },
                        new
                        {
                            ShopId = 95,
                            MusicType = "Omnis cumque consequatur minus quis aliquam.",
                            Name = "Pouros LLC",
                            PartOfTown = "Sapiente qui accusantium architecto odio.",
                            StoreType = "Perferendis eaque sit tempore sed minima repellat debitis laborum magnam."
                        },
                        new
                        {
                            ShopId = 96,
                            MusicType = "Illum quo praesentium in.",
                            Name = "Homenick LLC",
                            PartOfTown = "Et dolorum totam tempore quos dolorem veniam rerum eum.",
                            StoreType = "Aspernatur molestias enim dolores quod facere officiis excepturi non."
                        },
                        new
                        {
                            ShopId = 97,
                            MusicType = "Voluptatibus qui repellat omnis hic nostrum et dolor rerum.",
                            Name = "O'Conner, Wiza and Frami",
                            PartOfTown = "Natus quidem neque suscipit ratione.",
                            StoreType = "Omnis et ut labore laboriosam necessitatibus sed ad illum."
                        },
                        new
                        {
                            ShopId = 98,
                            MusicType = "Natus molestiae autem harum eveniet omnis earum unde.",
                            Name = "Schmitt-Pagac",
                            PartOfTown = "Quasi corrupti quia ullam sed sit temporibus totam est tenetur.",
                            StoreType = "Occaecati aut rem veniam dolor."
                        },
                        new
                        {
                            ShopId = 99,
                            MusicType = "Expedita adipisci aut sed quia ea molestiae sapiente occaecati mollitia.",
                            Name = "Hills Group",
                            PartOfTown = "Possimus et illo sed.",
                            StoreType = "Suscipit in ullam molestiae porro tempore dolorum."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
