// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortlandLocalShopsApi.Models;

#nullable disable

namespace PortlandLocalShopsApi.Migrations
{
    [DbContext(typeof(PortlandLocalShopsApiContext))]
    [Migration("20230401001838_seedDataOnceMore")]
    partial class seedDataOnceMore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PortlandLocalShopsApi.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MusicType")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PartOfTown")
                        .HasColumnType("longtext");

                    b.Property<string>("StoreType")
                        .HasColumnType("longtext");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            ShopId = 5,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Nicolas Group",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 6,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Lind-Torp",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 7,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Wilkinson LLC",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 8,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Welch, Stiedemann and Cassin",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 9,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Bauch-Hermann",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 10,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Koepp-Friesen",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 11,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "D'Amore, DuBuque and O'Kon",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 12,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Kilback-Rosenbaum",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 13,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Lockman, Abernathy and Lynch",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 14,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Graham Group",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 15,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Barton, Stroman and Dickens",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 16,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Hegmann Inc and Sons",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 17,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Gorczany, Lebsack and Reichel",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 18,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Homenick Inc and Sons",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 19,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Lowe LLC",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 20,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Ondricka-Wisozk",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 21,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Torp Inc and Sons",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 22,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Ernser Group",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 23,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Thompson-Abernathy",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 24,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Ledner-Flatley",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 25,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Lockman-Schamberger",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 26,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Jaskolski-Rodriguez",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 27,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Goodwin, Aufderhar and Upton",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 28,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Nikolaus LLC",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 29,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Grant Inc and Sons",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 30,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Bergstrom, Conroy and Greenfelder",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 31,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Raynor LLC",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 32,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Cartwright, Jacobi and Skiles",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 33,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Hackett LLC",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 34,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Collins, Heaney and Kautzer",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 35,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Kassulke, Lubowitz and Kertzmann",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 36,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Wuckert, Bradtke and Gorczany",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 37,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Nicolas LLC",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 38,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Beahan LLC",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 39,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Hane-Greenfelder",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 40,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Doyle Inc and Sons",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 41,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Bergstrom LLC",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 42,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Lynch-Conroy",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 43,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Stamm Group",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 44,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Auer-Jaskolski",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 45,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Frami Group",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 46,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Pfannerstill, Pollich and Roberts",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 47,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Mraz Group",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 48,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Kub LLC",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 49,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Davis Inc and Sons",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 50,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Herman Inc and Sons",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 51,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Boyle-Deckow",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 52,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Pouros, Stark and Herman",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 53,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Kling Group",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 54,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Kiehn-Boyle",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 55,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Wintheiser, Dach and Parisian",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 56,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Carroll LLC",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 57,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Cronin-Harvey",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 58,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Stoltenberg-Fritsch",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 59,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Purdy-Sanford",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 60,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Heidenreich LLC",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 61,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Breitenberg Inc and Sons",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 62,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Hane LLC",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 63,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Kuphal-Schmidt",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 64,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Baumbach Group",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 65,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Adams LLC",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 66,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Hessel, Cronin and Jenkins",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 67,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Pfeffer, Spinka and Mohr",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 68,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Stoltenberg Group",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 69,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Macejkovic Inc and Sons",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 70,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Olson Group",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 71,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Upton, Okuneva and Luettgen",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 72,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Howe-Howell",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 73,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Smitham, Kuhn and Ortiz",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 74,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Hirthe Inc and Sons",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 75,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Farrell-Cummerata",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 76,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Veum, Olson and Wiegand",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 77,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Jones, Kilback and Harber",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 78,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Romaguera LLC",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 79,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Quitzon-Reichert",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 80,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Ebert Group",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 81,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Fay, Blanda and Lang",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 82,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Block Group",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 83,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Brekke Group",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 84,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Weimann Group",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 85,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Harvey, King and Wunsch",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 86,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Morissette Group",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 87,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Bernier, Daugherty and Hoeger",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 88,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Stanton, Hamill and Gusikowski",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 89,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Kunze LLC",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 90,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Turner, Ledner and Nicolas",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 91,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Zemlak, Emard and Balistreri",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 92,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Sporer, Gibson and Grimes",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 93,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Raynor-Gulgowski",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 94,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Cremin, Pfeffer and Maggio",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 95,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Kilback, Stiedemann and Rodriguez",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 96,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Greenfelder-Bradtke",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 97,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Crona-Schinner",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 98,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Adams, McGlynn and Goldner",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        },
                        new
                        {
                            ShopId = 99,
                            MusicType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            Name = "Schaefer LLC",
                            PartOfTown = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]",
                            StoreType = "Faker.Extensions.EnumerableExtensions+<Times>d__0`1[System.String]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
