// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortlandLocalShopsApi.Models;

#nullable disable

namespace PortlandLocalShopsApi.Migrations
{
    [DbContext(typeof(PortlandLocalShopsApiContext))]
    [Migration("20230331222819_fixSytaxIssues")]
    partial class fixSytaxIssues
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PortlandLocalShopsApi.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MusicType")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PartOfTown")
                        .HasColumnType("longtext");

                    b.Property<string>("StoreType")
                        .HasColumnType("longtext");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            ShopId = 1,
                            MusicType = "various, singer-songwriter, guitar-bass-drums",
                            Name = "doug fir lounge",
                            PartOfTown = "e, east",
                            StoreType = "music venue"
                        },
                        new
                        {
                            ShopId = 2,
                            MusicType = "various, salsa, timba, singer-songwriter, guitar-bass-drums",
                            Name = "mississippi pizza",
                            PartOfTown = "ne, northeast",
                            StoreType = "pizza restaurant, music venue"
                        },
                        new
                        {
                            ShopId = 3,
                            MusicType = "various, funk, salsa, guitar-bass-drums",
                            Name = "the goodfoot",
                            PartOfTown = "ne, northeast",
                            StoreType = "bar, music venue"
                        },
                        new
                        {
                            ShopId = 4,
                            MusicType = "jazz",
                            Name = "the 1905",
                            PartOfTown = "ne, northeast",
                            StoreType = "bar, pizza, music venue"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
